echo ""
echo "Initializing directories..."
TOOL_DIR="$(dirname $(pwd))"
echo -e "${LIGHT_GREEN}"
echo "Your project's root directory:"
read PROJECT_ROOT_DIR
echo -e "${LIGHT_BLUE}"
echo "Tool directory: ${TOOL_DIR}"
echo "Project root dir: ${PROJECT_ROOT_DIR}"
echo "Directory initialization completed."
