#!/bin/bash

set -e
~~~include file~~~

help() {
  echo "ProjectInit.sh Project CLI"
  echo "Generated by ProjectInit.sh Version:~~~projectinit version~~~"
  echo "----------"
  echo ""
  echo "Overview of features:"
  ~~~help for feature~~~
}

main() {
  if [[ -z "$1" ]]; then
    echo "No feature selected. Nothing is executed."
    echo "Run 'sh projectinit_cli.sh help' to see the list of available features."
    exit
  fi

  if declare -f "$1" > /dev/null; then
    "$@"
  else
    echo "You have asked for invalid feature: $1"
    exit 2
  fi
}

main "$@"