= Development rules and guidelines
:toc:
:toclevels: 5

== Introduction

These rules and guidelines will help and guide you when implementing features and working on ProjectInit.sh development.

The keywords "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and
"OPTIONAL" in this document are to be interpreted as described in link:https://www.ietf.org/rfc/rfc2119.txt[RFC 2119].

== General user experience

. All questions a user should answer when running ProjectInit MUST be asked before any changes to the filesystem are
made.

== Prompts

. All "yes/no" prompts MUST implement the following acceptable input:
- for "yes": `"y"|"yes"|"yup"|"yeah"|"1"`
- for "no": `"n"|"no"|"nope"|"2"`

== Variables

. All global variable names MUST start with `projectinit_`.
. All global variable names MUST use `snake_case` and be lowercase. When a variable is in uppercase, it SHOULD mean that
it's holding an environment variable.
. You SHOULD reuse existing global variables whenever possible. When you are developing a new feature, take a look at
link:globals.adoc[Global variables documentation] first and see if any of the already existing global variables can be
used.

== Templates

. All placeholders inside templates MUST be placed between a pair of 3 tilde characters. Example:
`\~~~your template placeholder\~~~`