#!/bin/bash

cd /usr/src/symfony_temp_install || exit 1
#composer require --no-cache symfony/orm-pack
composer require --dev --no-cache fakerphp/faker
composer require --dev --no-cache symfony/maker-bundle
#composer require --dev --no-cache rector/rector
#composer require --no-cache doctrine/mongodb-odm-bundle
~~~install composer library~~~
cd /usr/src/app || exit 1
cp -a /usr/src/symfony_temp_install/* /usr/src/app/ || exit 1
cp -a /usr/src/symfony_temp_install/.[!.]* /usr/src/app/ || exit 1
echo "ProjectInit.sh installed Symfony ~~~framework version~~~ successfully. Creating the environment..."
echo "Note: If this process stalls for more than 2 seconds, deselect the terminal window and activate it again..."