echo ""
echo "Configuring Git user..."
git config user.name "${GIT_USER_NAME}"
git config user.email "${GIT_USER_EMAIL}"
echo "User name: ${GIT_USER_NAME}"
echo "User email: ${GIT_USER_EMAIL}"
echo "Git user configured."
